# Generated by Django 6.1.1 on 2026-09-27 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='شرح تراکنش')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ')),
                ('transactionType', models.CharField(choices=[('income', 'درآمد / فروش'), ('expense', 'هزینه / خرید')], max_length=10, verbose_name='نوع تراکنش')),
                ('paymentMethod', models.CharField(choices=[('cash', 'نقدی'), ('pos', 'کارتخوان'), ('credit', 'نسیه / حساب دفتری')], default='pos', max_length=10, verbose_name='نوع پرداخت')),
                ('customerName', models.CharField(blank=True, max_length=150, null=True, verbose_name='نام مشتری')),
                ('date', models.DateField(verbose_name='تاریخ تراکنش')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت در سیستم')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='حسابدار / کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeName', models.CharField(max_length=200, verbose_name='نام فروشگاه / شرکت')),
                ('phoneNumber', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره تماس')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
